### ISSUE TITLE
Document: "Why the system is correct"

### ISSUE THREAD

**Issue by TylerNakamura** [TylerNakamura/Calendar-Event-File-Generator#17]
The document should be in a pdf that can be committed to the repository. The document needs to explain why the system is correct. The document also needs to explain how the system is tested and what the respective results were.

**Comment by IHoffman5214** [comment]
I am in the process of writing this now.

**Comment by TylerNakamura** [comment]
Awesome! Thanks for letting me know. Write here if you have any questions

**Comment by IHoffman5214** [comment]
A pull request for the .pdf has been submitted. Feel free to revise anything you deem necessary or let me know if there is something you would like me to change. Also, it feels a little short but the assignment was so vague that I was unsure what to add. If you have anything to add or have a suggestion for me to add something, go ahead and go for it.

**Comment by TylerNakamura** [comment]
Looks good. Nice work! We just got to get this video out of the way now :smile:
